name: Deploy to Vercel
run-name: ${{ github.actor }} is deploying website to Vercel.
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# on:
  # schedule:
  #   - cron: '30 15 * * *' # 每天臺灣時間23:00執行(UTC+8)
on: [push]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"

      - name: Install Rakudo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: rakudo
          version: 1.0

      - name: Fetch csv
        run: raku update-data.raku

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
